#!/usr/bin/env bash

set -e

setupNvm() {
  # nvm is available through the GitHub virtual environment
  # see https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

  nvm install
  nvm use
}

setupNvm

npm ci
# These steps should have passed at the PR level.
# Re-run them for sanity.
npm run build
npm run test
npm run lint
npm run release
npm run release:docs
