#!/usr/bin/env bash

set -e

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
ROOT_DIR=$DIR/..

preamble() {
  "${DIR}"/check-yarn-lock
}

runIntegrationTest() {
  (
    cd "$ROOT_DIR/tools/integration-test"
    ./script/ci
  )
}

main() {
  preamble

  npm ci
  npm run build
  npm run lint
  npm run test:custom-lint-rule
  npm run test

  runIntegrationTest
}

main
