#!/usr/bin/env bash

set -e

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
ROOT_DIR=$DIR/..

preamble() {
  "${DIR}"/check-yarn-lock
  "${DIR}"/check-aws-cdk
}

setupNvm() {
  # nvm is available through the GitHub virtual environment
  # see https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

  nvm install
  nvm use
}

runIntegrationTest() {
  (
    cd "$ROOT_DIR/integration-test"
    ./script/ci
  )
}

main() {
  preamble
  setupNvm

  npm ci
  npm run build
  npm run lint
  npm run test:custom-lint-rule
  npm run test

  runIntegrationTest
}

main
