#!/usr/bin/env node

const { readFile, writeFile } = require("fs/promises");
const path = require("path");
const { execSync } = require("child_process");

async function main () {
  const readmePath = path.join(__dirname, "..", "README.md")
  const readme = (await readFile(readmePath)).toString()

  console.log(`Updating CLI instructions in ${readmePath}`);

  const startMark = "<!-- cli -->";
  const stopMark = "<!-- clistop -->";
  const codeBlock = "```";

  const rawCliHelp = execSync("npm run --silent cli:dev -- --help").toString();
  const cliHelp = rawCliHelp.replace(/index\.ts/g, "@guardian/cdk");

  const content = [codeBlock, cliHelp, codeBlock];

  if(readme.includes(startMark) && readme.includes(stopMark)){
    // Find text between markers and replace it with the start marker
    const re = new RegExp(`${startMark}(.|\n)*${stopMark}`, "m");
    const resetReadme = readme.replace(re, startMark);

    // replace the now singular start marker with the start marker, content and stop marker
    const updatedReadme = resetReadme.replace(startMark, [startMark, ...content, stopMark].join("\n"));

    // save changes
    await writeFile(readmePath, updatedReadme);
    console.log(`Changes written to ${readmePath}`);
  }
}

main()
  .then(() => {
    console.log("Done");
  })
  .catch((err) => {
    console.error(err);
  });
