#!/usr/bin/env bash

set -e

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

"${DIR}"/check-yarn-lock

if npm whoami &>/dev/null; then
  rm -rf ./lib
  npm run release
else
  echo "You are not logged into npm!"
  echo "  Run 'npm login' first!"
fi
