#!/usr/bin/env bash

set -e

EXTRA_ARGS=""
if [[ $# -gt 0 ]] ; then
  # npm requires `--` for argument passing
  # see https://docs.npmjs.com/cli/v6/commands/npm-run-script
  EXTRA_ARGS="-- $*"
fi

# only install dependencies when running in CI (currently GitHub Actions)
# see https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables
if [ $CI ] ; then
  npm ci
fi

# shellcheck disable=SC2086
npm run test $EXTRA_ARGS
