name: Create and publish a devx-logs (for ECS) Docker image

on:
  # Run manually
  workflow_dispatch:

  push:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Docker
        uses: docker/setup-docker-action@v5
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and tag Docker image for ECR
        run: docker buildx build --load -t logging:latest tools/logging

      - name: Publish image to ECR
        uses: guardian/actions-ecr/push@v1.0.1
        with:
          app: logging
          roleArn: ${{ secrets.GU_ARTIFACTS_ROLE_ARN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
