on:
  schedule:
    # At 10:00 on day-of-month 10.
    # See https://crontab.guru/#0_10_10_*_*
    - cron: '0 10 10 * *'

  # for testing
  workflow_dispatch:
  pull_request:
jobs:
  update-aws-cdk:
    runs-on: ubuntu-latest
    name: Bump CDK versions
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: "AWS CDK update"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./script/update-aws-cdk
